### ISSUE TITLE
Strange Source/Config Behaviour

### ISSUE THREAD

**Issue by i-am-tom** [ckald/pyccoon#1]
When trying to run Pyccoon on a project, after some digging, I found that, by default, the `.pyccoon` file is expected to be inside the project's source folder. The normal project layout -- in my opinion -- would be more like this:

```
myproject/
    source/
    test/
    .pyccoon
```

The way that this works with other projects, such as _py.test_, is that the cwd is searched to find the dot file. Furthermore, keeping them separate and not requiring me to set the parent `myproject` folder as the source means that I don't have to add several more expressions to the `skip_files` list in the config file.

---

To get this behaviour, I simply changed [line 109](https://github.com/ckald/pyccoon/blob/master/pyccoon/pyccoon.py#L109) to this:

``` python
        config_file = os.path.join(os.getcwd(), self.config_file)
```

If you agree with this change, I'm happy to submit a PR and update any tests that might depend on the old behaviour :)

**Comment by ckald** [comment]
I think we should also add an optional command line argument "-c" to override new behaviour as well. It would be great if you will supply the PR. 

Curiosity: for what kind of language and project do you use pyccon?

**Comment by i-am-tom** [comment]
No problem, I'll get to it this weekend :)

I'm writing Python for a university project and, coming mainly from Javascript, wanted to see what was "out there". When Pycco's `--help` flag failed to show without raising exceptions, I stumbled across this project!

**Comment by ckald** [comment]
I see. Small Python project is perfectly fine for this kind of documentation generator. I use pyccoon for my university project too: http://ckald.github.io/pyBBN/index.html

**Comment by i-am-tom** [comment]
Nice! I've submitted [my PR](https://github.com/ckald/pyccoon/pull/2) and it turns out that the `-c` flag still works happily (though it obviously now works in relation to the project root), so I'll close this issue. Thanks!
