### ISSUE TITLE
feature request: table of contents

### ISSUE THREAD

**Issue by danshapero** [ckald/pyccoon#16]
I was just having a look at another Docco-inspired project, [marginalia](https://gdeer81.github.io/marginalia). Although marginalia is strictly for clojure code, it has the nice feature of putting a hyperlinked table of contents at the top of the documentation based on the headers used in the markdown of the source file. I use pyccoon for documenting a project of mine and this would be a really helpful feature.

Thanks for all your great work on this project!

**Comment by ckald** [comment]
We have a table of contents in the header. Do you want it to be immediately visible?

Thanks! I would love to see your docs — probably I'll get ideas for improvements from your use case

**Comment by danshapero** [comment]
Ah I see the dropdown menu for it, missed that before!

I'm writing a library for glacier and ice sheet modelling called [icepack](https://github.com/danshapero/icepack), and I'm using pyccoon to document the [example code](https://github.com/danshapero/icepack-examples/tree/master/examples). The MathJax support is especially helpful compared to what's available in pycco.
