### ISSUE TITLE
Linebreaks in commends/documentation

### ISSUE THREAD

**Issue by cryptonomicon314** [ckald/pyccoon#4]
Currently, the documentation sections (left side) of the .html files generated by pyccoon obey the following css rule (defined in pyccoon.css)

``` css
.docs p {
   white-space: pre-wrap;
}
```

This means linebreaks are respected by the browser when rendering.
This seams counterintuitive to me, and the only way to go against this is to end each line in a comment block with the character `\`. Is there any chance of changing this in a future version, or making it configurable?

If you really want to add a new paragraph in a block comment, you can always do:

``` python
# A paragraph
#
# A new Paragraph
```

which is consistent with normal markdown usage.

**Comment by ckald** [comment]
Yeah, I was thinking about this quite a lot, thanks for reporting. I believe I encountered some kind of problem when the regular thing did not work. Probably it had something to do with formulas in comments and huge comment blocks when you add explicit linebreaks.

I will take a look at it and at least will make a config option for this. PR would be very welcome, this change requires mostly to add conditions for few pieces of code

**Comment by ckald** [comment]
The other thing inconsistent with the regular Markdown in the released version of pyccoon is the titles syntax. I am trying to fix that too, but with current algorithm of parsing the comments it is hard to do this (because e.g. python uses the same delimiter for comments). Looks like a big rewrite is required here

**Comment by cryptonomicon314** [comment]
I don't think you'd have to change anything in the code apart from the css rule I mentioned above into:

``` css
.docs p {
   white-space: normal;
}
```

I get the expected result for my files when I turn that rule off with my browser's developer tools.
What else do you say needs changing?

The markdown headers are only a problem inside multiline comments
You can use the other kind of markdown titles

``` markdown
This is an H1
=============

This is an H2
-------------
```

**Comment by cryptonomicon314** [comment]
I can submit a PR to change the CSS, but I don't understand the code enough to antecipate unintended ramifications

**Comment by ckald** [comment]
Probably you should also deactivate the LineConnector markdown extension that makes the "\" symbol work. But it might be enough just to change the CSS. But for backwards compatibility sake this should be optional. I wonder if the page css should be also preprocessed depending on config options.

Other option is to allow to set custom css file with additional rules. This will cover your issue and will not break anything.

**Comment by cryptonomicon314** [comment]
Setting a custom CSS file is the most powerful option, and would be useful for further customizations, but is kind of overkill for this problem. Making it configurable in the .pyccoon file is good enough for now, I guess.

> I wonder if the page css should be also preprocessed depending on config options.

You could turn the CSS file into a pystache template (I prefer jinja, but since you're already using pystache that's the way to go).

**Comment by cryptonomicon314** [comment]
When I have the time I'll submit a PR.
Your project is really amazing, and your design is beautiful. I look forward to colaborate with you on this.

**Comment by ckald** [comment]
I believe that initial design credit belongs to Nick Fitzgerald, the author of pycco https://fitzgen.github.io/pycco/ . I did only few adjustments.

**Comment by cryptonomicon314** [comment]
Ok, credit where it's due, then.

**Comment by ckald** [comment]
It's kinda credited on this page http://ckald.github.io/pyccoon/ , do you think I should do that more explicitly?

**Comment by cryptonomicon314** [comment]
No, no! I was referring myself. It was stupid of me to credit you instead of the original author. I was the one who didn't read closely enough
